delete from themes;
ALTER SEQUENCE themes_id_seq RESTART WITH 1;
ALTER SEQUENCE questions_id_seq RESTART WITH 1;
ALTER SEQUENCE answers_id_seq RESTART WITH 1;
insert into themes values (1, 'Java');
insert into themes values (2, 'География');
insert into questions values (1, 1, 'int - это...');
insert into questions values (2, 1, 'Выберите цикл с постусловием:');
insert into questions values (3, 1, 'Ключевое слово final в начале объявления метода...');
insert into questions values (4, 2, 'Столица Камбоджи');
insert into questions values (5, 2, 'Самая длинная и многоводная река Евразии');
insert into questions values (6, 2, 'Страны, с которыми Украина граничит на севере');
insert into answers values (1, 1, 'A', 'целочисленный тип данных с диапазоном значений от -128 до 127', false);
insert into answers values (2, 1, 'B', 'тип данных, определяющий числовое значение с плавающей точкой одинарной точности', false);
insert into answers values (3, 1, 'C', 'целочисленный тип данных с диапазоном значений от -2147483648 до 2147483647', true);
insert into answers values (4, 2, 'A', 'for(int i=0; i<10; i++) { }', false);
insert into answers values (5, 2, 'B', '{ } while(i<10)', true);
insert into answers values (6, 2, 'C', 'while(i<10) { }', false);
insert into answers values (7, 3, 'A', 'не позволяет вызвать его за пределами класса, в котором он объявлен', false);
insert into answers values (8, 3, 'B', 'предотвращает его переопределение', true);
insert into answers values (9, 3, 'C', 'позволяет вызвать данный метод лишь единожды', false);
insert into answers values (10, 4, 'A', 'Катманду', false);
insert into answers values (11, 4, 'B', 'Москва', false);
insert into answers values (12, 4, 'C', 'Пномпень', true);
insert into answers values (13, 5, 'A', 'Янцзы', true);
insert into answers values (14, 5, 'B', 'Днепр', false);
insert into answers values (15, 5, 'C', 'Волга', false);
insert into answers values (16, 6, 'A', 'Беларусь и Россия', true);
insert into answers values (17, 6, 'B', 'Румыния и Молдавия', false);
insert into answers values (18, 6, 'C', 'Словакия и Венгрия', false);